version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - run:
          name: "Trigger Build Circle-101"

          # Call to CircleCi API to trigger build based on `.circleci/config.yml` of CircleCI-101 repo
          command: "curl -X POST https://circleci.com/api/v1.1/project/github/alyssalew/CircleCI-101/build?circle-token=$CIRCLE_TOKEN"